export enum OvertimeType {
  REGULAR = 'REGULAR',
  WEEKEND = 'WEEKEND',
  HOLIDAY = 'HOLIDAY',
  PUBLIC_HOLIDAY = 'PUBLIC_HOLIDAY'
}

export enum ClaimStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PROCESSED = 'PROCESSED',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED'
}