export enum TravelType {
  LOCAL = 'LOCAL',
  INTERNATIONAL = 'INTERNATIONAL'
}

export enum TravelPurpose {
  CLIENT_MEETING = 'CLIENT_MEETING',
  TRAINING = 'TRAINING',
  CONFERENCE = 'CONFERENCE',
  PROJECT_IMPLEMENTATION = 'PROJECT_IMPLEMENTATION',
  SITE_VISIT = 'SITE_VISIT',
  BUSINESS_DEVELOPMENT = 'BUSINESS_DEVELOPMENT',
  EMERGENCY_SUPPORT = 'EMERGENCY_SUPPORT',
  OTHER = 'OTHER'
}

export enum AccommodationType {
  FULLY_PAID = 'FULLY_PAID',
  OUT_OF_POCKET = 'OUT_OF_POCKET',
  PER_DIEM_ONLY = 'PER_DIEM_ONLY'
}

export enum TravelMode {
  ROAD = 'ROAD',
  AIR = 'AIR',
  RAIL = 'RAIL',
  SEA = 'SEA'
}

export enum TransportMode {
  COMPANY_VEHICLE = 'COMPANY_VEHICLE',
  RENTAL_CAR = 'RENTAL_CAR',
  PUBLIC_TRANSPORT = 'PUBLIC_TRANSPORT',
  TAXI = 'TAXI',
  FLIGHT = 'FLIGHT',
  OTHER = 'OTHER'
}

export enum TravelStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  SETTLEMENT_PENDING = 'SETTLEMENT_PENDING',
  SETTLEMENT_APPROVED = 'SETTLEMENT_APPROVED',
  SETTLEMENT_REJECTED = 'SETTLEMENT_REJECTED',
  CLOSED = 'CLOSED'
}

export enum ApprovalAction {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  ESCALATE = 'ESCALATE',
  RETURN = 'RETURN',
  DELEGATE = 'DELEGATE'
}

export enum PaymentMethod {
  BANK_TRANSFER = 'BANK_TRANSFER',
  CHEQUE = 'CHEQUE',
  CASH = 'CASH',
  DIRECT_HOTEL_PAYMENT = 'DIRECT_HOTEL_PAYMENT'
}

export enum ExpenseCategory {
  ACCOMMODATION = 'ACCOMMODATION',
  MEALS = 'MEALS',
  TRANSPORT = 'TRANSPORT',
  FUEL = 'FUEL',
  PARKING = 'PARKING',
  TOLLS = 'TOLLS',
  COMMUNICATION = 'COMMUNICATION',
  PRINTING = 'PRINTING',
  ENTERTAINMENT = 'ENTERTAINMENT',
  INCIDENTALS = 'INCIDENTALS',
  OTHER = 'OTHER'
}

export enum Currency {
  MWK = 'MWK',
  USD = 'USD',
  ZAR = 'ZAR',
  EUR = 'EUR',
  GBP = 'GBP'
}

export enum TravelUrgency {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  URGENT = 'URGENT'
}

export enum RejectionReason {
  BUDGET_CONSTRAINT = 'BUDGET_CONSTRAINT',
  POLICY_VIOLATION = 'POLICY_VIOLATION',
  MISSING_INFORMATION = 'MISSING_INFORMATION',
  INSUFFICIENT_JUSTIFICATION = 'INSUFFICIENT_JUSTIFICATION',
  SCHEDULING_CONFLICT = 'SCHEDULING_CONFLICT',
  NO_APPROVAL_AUTHORITY = 'NO_APPROVAL_AUTHORITY',
  OTHER = 'OTHER'
}

export enum EscalationReason {
  URGENT_CLIENT_REQUIREMENT = 'URGENT_CLIENT_REQUIREMENT',
  POLICY_INTERPRETATION_NEEDED = 'POLICY_INTERPRETATION_NEEDED',
  HIGH_VALUE_REQUEST = 'HIGH_VALUE_REQUEST',
  COMPLEX_SITUATION = 'COMPLEX_SITUATION',
  MANAGEMENT_OVERRIDE = 'MANAGEMENT_OVERRIDE',
  OTHER = 'OTHER'
}

export enum WorkflowStageType {
  APPROVAL = 'APPROVAL',
  VERIFICATION = 'VERIFICATION',
  NOTIFICATION = 'NOTIFICATION'
}

export enum WorkflowStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ESCALATED = 'ESCALATED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED'
}

export enum ApprovalRuleType {
  MANAGERIAL_LEVEL = 'MANAGERIAL_LEVEL',
  ROLE_BASED = 'ROLE_BASED',
  GRADE_BASED = 'GRADE_BASED',
  SPECIFIC_USER = 'SPECIFIC_USER',
  AMOUNT_BASED = 'AMOUNT_BASED'
}