import { User, UserRole } from "@/types/auth/user"

export const PERMISSIONS = {
  // System level
  SYSTEM_FULL_ACCESS: 'system:full_access',
  
  // User management
  USERS_MANAGE_SUPER_ADMINS: 'users:manage_super_admins',
  USERS_MANAGE_ALL: 'users:manage_all',
  USERS_MANAGE_PERMISSIONS: 'users:manage_permissions',
  
  // Role management
  ROLES_MANAGE_ALL: 'roles:manage_all',
  
  // Employee management
  EMPLOYEES_MANAGE_ALL: 'employees:manage_all',
  
  // Department management
  DEPARTMENT_MANAGE: 'department:manage',
  
  // Team management
  TEAM_MANAGE: 'team:manage',
  
  // Direct reports
  DIRECT_REPORTS_MANAGE: 'direct_reports:manage',
  
  // Approvals
  APPROVALS_DEPARTMENT: 'approvals:department',
  APPROVALS_TEAM: 'approvals:team',
  APPROVALS_DIRECT_REPORTS: 'approvals:direct_reports',
  
  // Profile
  PROFILE_MANAGE: 'profile:manage',
  
  // Requests
  REQUESTS_CREATE: 'requests:create',
  
  // Additional permissions for your system
  LOANS_MANAGE: 'loans:manage',
  LOANS_APPROVE: 'loans:approve',
  TRAVEL_MANAGE: 'travel:manage',
  TRAVEL_APPROVE: 'travel:approve',
  OVERTIME_MANAGE: 'overtime:manage',
  OVERTIME_APPROVE: 'overtime:approve',
  PAYROLL_MANAGE: 'payroll:manage',
  REPORTS_VIEW: 'reports:view',
  REPORTS_GENERATE: 'reports:generate',
  AUDIT_LOGS_VIEW: 'audit_logs:view',
  SETTINGS_MANAGE: 'settings:manage',
  DEPARTMENT_VIEW: 'department:view',
  POSITION_VIEW: 'position:view',
  POSITION_MANAGE: 'position:manage',
  GRADE_VIEW: 'grade:view',
  GRADE_MANAGE: 'grade:manage',
  
  // Employee Permissions
  EMPLOYEES_VIEW: 'employees:view',
  EMPLOYEES_MANAGE_DEPARTMENT: 'employees:manage_department',
  
  // System Permissions

  WORKFLOW_INSTANCES_CREATE: 'workflow:instances_create',
  WORKFLOW_INSTANCES_VIEW_ALL: 'workflow:instances_view_all',
  WORKFLOW_INSTANCES_VIEW_DEPARTMENT: 'workflow:instances_view_department',
  WORKFLOW_INSTANCES_VIEW_TEAM: 'workflow:instances_view_team',
  WORKFLOW_INSTANCES_APPROVE: 'workflow:instances_approve',
  WORKFLOW_INSTANCES_REJECT: 'workflow:instances_reject', // You already have this one
  WORKFLOW_INSTANCES_CANCEL: 'workflow:instances_cancel',
  
  WORKFLOW_DEFINITIONS_MANAGE: 'workflow:definitions_manage',
  WORKFLOW_DEFINITIONS_VIEW: 'workflow:definitions_view',
  WORKFLOW_DEFINITIONS_CREATE: 'workflow:definitions_create',
  WORKFLOW_DEFINITIONS_EDIT: 'workflow:definitions_edit',
  WORKFLOW_DEFINITIONS_DELETE: 'workflow:definitions_delete',
  WORKFLOW_DEFINITIONS_ACTIVATE: 'workflow:definitions_activate',
  WORKFLOW_DEFINITIONS_DEACTIVATE: 'workflow:definitions_deactivate',
  
  DELEGATIONS_MANAGE: 'delegations:manage',
  DELEGATIONS_CREATE: 'delegations:create',
  DELEGATIONS_VIEW: 'delegations:view',
  DELEGATIONS_REVOKE: 'delegations:revoke',

} as const

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS]

// Role to permissions mapping
export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [UserRole.SUPER_SUPER_ADMIN]: [
    PERMISSIONS.SYSTEM_FULL_ACCESS,
    PERMISSIONS.USERS_MANAGE_SUPER_ADMINS,
    PERMISSIONS.USERS_MANAGE_ALL,
    PERMISSIONS.ROLES_MANAGE_ALL,
    PERMISSIONS.USERS_MANAGE_PERMISSIONS,
    PERMISSIONS.EMPLOYEES_MANAGE_ALL,
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.APPROVALS_DEPARTMENT,
    PERMISSIONS.TEAM_MANAGE,
    PERMISSIONS.APPROVALS_TEAM,
    PERMISSIONS.DIRECT_REPORTS_MANAGE,
    PERMISSIONS.APPROVALS_DIRECT_REPORTS,
    PERMISSIONS.PROFILE_MANAGE,
    PERMISSIONS.REQUESTS_CREATE,
    PERMISSIONS.LOANS_MANAGE,
    PERMISSIONS.LOANS_APPROVE,
    PERMISSIONS.TRAVEL_MANAGE,
    PERMISSIONS.TRAVEL_APPROVE,
    PERMISSIONS.OVERTIME_MANAGE,
    PERMISSIONS.OVERTIME_APPROVE,
    PERMISSIONS.PAYROLL_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.AUDIT_LOGS_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
  ],
  
  [UserRole.SUPER_ADMIN]: [
    PERMISSIONS.USERS_MANAGE_ALL,
    PERMISSIONS.ROLES_MANAGE_ALL,
    PERMISSIONS.EMPLOYEES_MANAGE_ALL,
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.APPROVALS_DEPARTMENT,
    PERMISSIONS.TEAM_MANAGE,
    PERMISSIONS.APPROVALS_TEAM,
    PERMISSIONS.DIRECT_REPORTS_MANAGE,
    PERMISSIONS.APPROVALS_DIRECT_REPORTS,
    PERMISSIONS.PROFILE_MANAGE,
    PERMISSIONS.REQUESTS_CREATE,
    PERMISSIONS.LOANS_MANAGE,
    PERMISSIONS.LOANS_APPROVE,
    PERMISSIONS.TRAVEL_MANAGE,
    PERMISSIONS.TRAVEL_APPROVE,
    PERMISSIONS.OVERTIME_MANAGE,
    PERMISSIONS.OVERTIME_APPROVE,
    PERMISSIONS.PAYROLL_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.AUDIT_LOGS_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
  ],
  
  [UserRole.SYSTEM_ADMIN]: [
    PERMISSIONS.EMPLOYEES_MANAGE_ALL,
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.TEAM_MANAGE,
    PERMISSIONS.PROFILE_MANAGE,
    PERMISSIONS.REQUESTS_CREATE,
    PERMISSIONS.LOANS_MANAGE,
    PERMISSIONS.TRAVEL_MANAGE,
    PERMISSIONS.OVERTIME_MANAGE,
    PERMISSIONS.PAYROLL_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.WORKFLOW_DEFINITIONS_MANAGE,
    PERMISSIONS.WORKFLOW_DEFINITIONS_VIEW,
    PERMISSIONS.WORKFLOW_DEFINITIONS_CREATE,
    PERMISSIONS.WORKFLOW_DEFINITIONS_EDIT,
    PERMISSIONS.WORKFLOW_DEFINITIONS_DELETE,
    PERMISSIONS.WORKFLOW_DEFINITIONS_ACTIVATE,
    PERMISSIONS.WORKFLOW_DEFINITIONS_DEACTIVATE,
    PERMISSIONS.WORKFLOW_INSTANCES_VIEW_ALL,
    PERMISSIONS.WORKFLOW_INSTANCES_APPROVE,
    PERMISSIONS.WORKFLOW_INSTANCES_REJECT,
    PERMISSIONS.WORKFLOW_INSTANCES_CANCEL,
    PERMISSIONS.DELEGATIONS_MANAGE
  ],
  
  [UserRole.HR_ADMIN]: [
    PERMISSIONS.EMPLOYEES_MANAGE_ALL,
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.TEAM_MANAGE,
    PERMISSIONS.PROFILE_MANAGE,
    PERMISSIONS.REQUESTS_CREATE,
    PERMISSIONS.LOANS_APPROVE,
    PERMISSIONS.TRAVEL_APPROVE,
    PERMISSIONS.OVERTIME_APPROVE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.WORKFLOW_DEFINITIONS_MANAGE,
    PERMISSIONS.WORKFLOW_DEFINITIONS_VIEW,
    PERMISSIONS.WORKFLOW_DEFINITIONS_CREATE,
    PERMISSIONS.WORKFLOW_DEFINITIONS_EDIT,
    PERMISSIONS.WORKFLOW_DEFINITIONS_DELETE,
    PERMISSIONS.WORKFLOW_INSTANCES_VIEW_ALL,
    PERMISSIONS.WORKFLOW_INSTANCES_APPROVE,
    PERMISSIONS.WORKFLOW_INSTANCES_REJECT,
    PERMISSIONS.WORKFLOW_INSTANCES_CANCEL
  ],
  
  [UserRole.HR_MANAGER]: [
    PERMISSIONS.EMPLOYEES_MANAGE_ALL,
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.APPROVALS_DEPARTMENT,
    PERMISSIONS.TEAM_MANAGE,
    PERMISSIONS.APPROVALS_TEAM,
    PERMISSIONS.PROFILE_MANAGE,
    PERMISSIONS.REQUESTS_CREATE,
    PERMISSIONS.LOANS_APPROVE,
    PERMISSIONS.TRAVEL_APPROVE,
    PERMISSIONS.OVERTIME_APPROVE,
    PERMISSIONS.REPORTS_VIEW,
  ],
  
  [UserRole.FINANCE_MANAGER]: [
    PERMISSIONS.LOANS_MANAGE,
    PERMISSIONS.LOANS_APPROVE,
    PERMISSIONS.TRAVEL_APPROVE,
    PERMISSIONS.OVERTIME_APPROVE,
    PERMISSIONS.PAYROLL_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
  ],
  
  [UserRole.DEPARTMENT_HEAD]: [
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.APPROVALS_DEPARTMENT,
    PERMISSIONS.TEAM_MANAGE,
    PERMISSIONS.APPROVALS_TEAM,
    PERMISSIONS.DIRECT_REPORTS_MANAGE,
    PERMISSIONS.APPROVALS_DIRECT_REPORTS,
    PERMISSIONS.PROFILE_MANAGE,
    PERMISSIONS.REQUESTS_CREATE,
    PERMISSIONS.REPORTS_VIEW,
  ],
  
  [UserRole.MANAGER]: [
    PERMISSIONS.TEAM_MANAGE,
    PERMISSIONS.APPROVALS_TEAM,
    PERMISSIONS.DIRECT_REPORTS_MANAGE,
    PERMISSIONS.APPROVALS_DIRECT_REPORTS,
    PERMISSIONS.PROFILE_MANAGE,
    PERMISSIONS.REQUESTS_CREATE,
    PERMISSIONS.REPORTS_VIEW,
  ],
  
  [UserRole.SUPERVISOR]: [
    PERMISSIONS.DIRECT_REPORTS_MANAGE,
    PERMISSIONS.APPROVALS_DIRECT_REPORTS,
    PERMISSIONS.PROFILE_MANAGE,
    PERMISSIONS.REQUESTS_CREATE,
    PERMISSIONS.WORKFLOW_INSTANCES_CREATE,
    PERMISSIONS.WORKFLOW_INSTANCES_VIEW_TEAM,
    PERMISSIONS.WORKFLOW_INSTANCES_APPROVE,
    PERMISSIONS.WORKFLOW_INSTANCES_REJECT,
    PERMISSIONS.DELEGATIONS_CREATE,
    PERMISSIONS.DELEGATIONS_VIEW,
  ],
  
  [UserRole.TRAVEL_ADMIN]: [
    PERMISSIONS.TRAVEL_MANAGE,
    PERMISSIONS.TRAVEL_APPROVE,
    PERMISSIONS.REQUESTS_CREATE,
    PERMISSIONS.REPORTS_VIEW,
  ],
  
  [UserRole.ADMIN_EMPLOYEE]: [
    PERMISSIONS.PROFILE_MANAGE,
    PERMISSIONS.REQUESTS_CREATE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.WORKFLOW_INSTANCES_CREATE,
    PERMISSIONS.WORKFLOW_INSTANCES_VIEW_TEAM,
    PERMISSIONS.WORKFLOW_INSTANCES_APPROVE,
    PERMISSIONS.WORKFLOW_INSTANCES_REJECT,
    PERMISSIONS.DELEGATIONS_CREATE,
    PERMISSIONS.DELEGATIONS_VIEW,
    PERMISSIONS.DELEGATIONS_REVOKE,
  ],
  
  [UserRole.EMPLOYEE]: [
    PERMISSIONS.PROFILE_MANAGE,
    PERMISSIONS.REQUESTS_CREATE,
  ],
}

// Helper functions
export function hasPermission(user: User | null, permission: Permission): boolean {
  if (!user) return false
  return user.permissions.includes(permission)
}

export function hasAnyPermission(user: User | null, permissions: Permission[]): boolean {
  if (!user) return false
  return permissions.some(permission => user.permissions.includes(permission))
}

export function hasAllPermissions(user: User | null, permissions: Permission[]): boolean {
  if (!user) return false
  return permissions.every(permission => user.permissions.includes(permission))
}

export function canAccessRoute(user: User | null, requiredPermissions: Permission[]): boolean {
  if (!user) return false
  if (user.permissions.includes(PERMISSIONS.SYSTEM_FULL_ACCESS)) return true
  return requiredPermissions.some(permission => user.permissions.includes(permission))
}

export function getUserRoleDisplay(role: UserRole): string {
  return role
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}